services:
  act_runner:
    image: gitea/act_runner:0.2.11
    container_name: act_runner
    privileged: true # Docker 내에서 다른 컨테이너를 시작하기 위해 Docker 소캣에 접근해야 하는데 그 때 필요한 권한 설정
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://10.10.110.52:3300" 
      GITEA_RUNNER_REGISTRATION_TOKEN: "wmJgNntP0CH0TmLSo4PkclF0TeHcgVyCG2wHxTXK"
      GITEA_RUNNER_NAME: "act_runner"
      #DOCKER_HOST: "tcp://0.0.0.0:2375"  # Docker API를 통한 접근
      #GITEA_RUNNER_LABELS: ubuntu-latest:docker
    volumes:
      - ./act-runner/data:/data
      - ./act-runner/cache:/root/.cache
      - ./config.yaml:/config.yaml
      # - ./daemon.json:/etc/docker/daemon.json
      # - ./var/run/docker.sock:/var/run/docker.sock 선생님 께서는 Vagrant(Linux 환경)를 통해 도커를 실행하기 때문에.. 필자는 로컬에서 수행하기에 필요 없음.
    networks:
      - gitea_network
    restart: unless-stopped

networks:
  gitea_network:
    external: true  # 외부 네트워크로 정의