services:
  act_runner:
    image: gitea/act_runner:0.2.11
    container_name: act_runner
    privileged: true # Docker 내에서 다른 컨테이너를 시작하기 위해 Docker 소캣에 접근해야 하는데 그 때 필요한 권한 설정
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://10.10.110.52:3300" 
      GITEA_RUNNER_REGISTRATION_TOKEN: "wmJgNntP0CH0TmLSo4PkclF0TeHcgVyCG2wHxTXK"
      GITEA_RUNNER_NAME: "act_runner"
      #GITEA_RUNNER_LABELS: ubuntu-latest:docker
    volumes:
      - ./act-runner/data:/data
      - ./act-runner/cache:/root/.cache
      - ./config.yaml:/config.yaml
      - ./var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea_network
    restart: unless-stopped

networks:
  gitea_network:
    external: true  # 외부 네트워크로 정의