services:
  gitea:
    build:
      context: .
      dockerfile: Dockerfile
    #image: gitea/gitea:1.21.10
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - "./data:/data"
      - "./app.ini:/data/gitea/conf/app.ini"
      - "./certs:/data/certs"
      # - "/etc/timezone:/etc/timezone:ro"
      # - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3300:3300"
      - "222:22"
    networks:
      - gitea_network  
    restart: unless-stopped

networks:
  gitea_network:  # 네트워크로 정의
      driver: bridge  