#
# .gitea/gitea-ci.yaml
#

name: Build And Test
run-name: ${{ gitea.actor }} is runs ci pipeline
#on: [ push ]
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - 'docs/**'
      - 'helm/**'


jobs:
  Gitea-Docker-Build-Push:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3       
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64          
          push: true
          tags: gnu96/gitea-docker-build-push-repo:${{gitea.run_number}} 
      - name: Update values.yaml
        run: |
          cd helm
          cat <<EOF > "image.yaml"
          image:
            repository: gnu96/gitea-docker-build-push-repo
            pullPolicy: IfNotPresent
            tag: ${{gitea.run_number}}
          EOF
          git config --global user.name 'gitea'
          git config --global user.email 'gitea@github.com'          
          git add image.yaml
          git commit -m "Update image.yaml"
          git push